import type { BuiltinImpl } from '../runtime.js'
import { llSay, llShout, llWhisper, llOwnerSay } from './chat.js'
import {
  llSetTimerEvent,
  llSleep,
  llGetTime,
  llGetAndResetTime,
  llResetTime,
} from './time.js'
import { llHTTPRequest, llHTTPResponse } from './http.js'
import { llListen, llListenRemove, llListenControl } from './listen.js'
import {
  llAbs,
  llFabs,
  llRound,
  llCeil,
  llFloor,
  llPow,
  llSqrt,
  llSin,
  llCos,
  llTan,
  llAsin,
  llAcos,
  llAtan2,
  llLog,
  llLog10,
  llFrand,
  llVecMag,
  llVecNorm,
  llVecDist,
  llRot2Euler,
  llEuler2Rot,
} from './math.js'
import {
  llStringLength,
  llSubStringIndex,
  llGetSubString,
  llDeleteSubString,
  llInsertString,
  llStringTrim,
  llToLower,
  llToUpper,
  llReplaceSubString,
  llEscapeURL,
  llUnescapeURL,
} from './strings.js'
import {
  llGetListLength,
  llList2Integer,
  llList2Float,
  llList2String,
  llList2Key,
  llList2Vector,
  llList2Rot,
  llList2List,
  llDeleteSubList,
  llListInsertList,
  llListReplaceList,
  llListFindList,
  llDumpList2String,
  llCSV2List,
  llParseString2List,
} from './lists.js'
import {
  llGetOwner,
  llGetCreator,
  llGetKey,
  llGetObjectName,
  llSetObjectName,
  llGetScriptName,
} from './identity.js'
import { llMessageLinked } from './linked.js'
import {
  llRequestAgentData,
  llRequestInventoryData,
  llRequestSimulatorData,
  llRequestUsername,
  llRequestDisplayName,
} from './dataserver.js'
import {
  llDetectedKey,
  llDetectedName,
  llDetectedOwner,
  llDetectedGroup,
  llDetectedPos,
  llDetectedRot,
  llDetectedVel,
  llDetectedType,
  llDetectedLinkNumber,
  llDetectedGrab,
  llDetectedTouchPos,
} from './detected.js'
import { llMD5String, llSHA1String, llSHA256String, llHMAC } from './hash.js'
import {
  llStringToBase64,
  llBase64ToString,
  llIntegerToBase64,
  llBase64ToInteger,
} from './base64.js'
import {
  llSetText,
  llSetObjectDesc,
  llGetObjectDesc,
  llDie,
  llResetScript,
} from './object.js'
import {
  llGetLinkNumber,
  llGetNumberOfPrims,
  llGetLinkKey,
  llGetLinkName,
} from './link-info.js'
import {
  llGetInventoryNumber,
  llGetInventoryName,
  llGetInventoryType,
  llGetInventoryKey,
  llGetInventoryCreator,
  llGetInventoryDesc,
  llGetInventoryAcquireTime,
  llGetInventoryPermMask,
  llGetNotecardLine,
  llGetNumberOfNotecardLines,
} from './inventory.js'
import {
  llResetOtherScript,
  llSetScriptState,
  llGetScriptState,
} from './script-control.js'
import {
  llLinksetDataWrite,
  llLinksetDataWriteProtected,
  llLinksetDataRead,
  llLinksetDataReadProtected,
  llLinksetDataDelete,
  llLinksetDataDeleteProtected,
  llLinksetDataDeleteFound,
  llLinksetDataReset,
  llLinksetDataAvailable,
  llLinksetDataCountKeys,
  llLinksetDataListKeys,
  llLinksetDataFindKeys,
  llLinksetDataCountFound,
} from './linksetdata.js'

/**
 * Map of `ll*` name → real implementation. Anything not in this map falls
 * through to the auto-generated stub (returns the documented default value
 * and records the call). User mocks (script.mock(...)) override either.
 */
export const REAL_BUILTINS: Readonly<Record<string, BuiltinImpl>> = {
  llSay,
  llShout,
  llWhisper,
  llOwnerSay,
  llSetTimerEvent,
  llSleep,
  llGetTime,
  llGetAndResetTime,
  llResetTime,
  llHTTPRequest,
  llHTTPResponse,
  llListen,
  llListenRemove,
  llListenControl,
  // math
  llAbs,
  llFabs,
  llRound,
  llCeil,
  llFloor,
  llPow,
  llSqrt,
  llSin,
  llCos,
  llTan,
  llAsin,
  llAcos,
  llAtan2,
  llLog,
  llLog10,
  llFrand,
  llVecMag,
  llVecNorm,
  llVecDist,
  llRot2Euler,
  llEuler2Rot,
  // strings
  llStringLength,
  llSubStringIndex,
  llGetSubString,
  llDeleteSubString,
  llInsertString,
  llStringTrim,
  llToLower,
  llToUpper,
  llReplaceSubString,
  llEscapeURL,
  llUnescapeURL,
  // lists
  llGetListLength,
  llList2Integer,
  llList2Float,
  llList2String,
  llList2Key,
  llList2Vector,
  llList2Rot,
  llList2List,
  llDeleteSubList,
  llListInsertList,
  llListReplaceList,
  llListFindList,
  llDumpList2String,
  llCSV2List,
  llParseString2List,
  // identity
  llGetOwner,
  llGetCreator,
  llGetKey,
  llGetObjectName,
  llSetObjectName,
  llGetScriptName,
  // linked
  llMessageLinked,
  // dataserver
  llRequestAgentData,
  llRequestInventoryData,
  llRequestSimulatorData,
  llRequestUsername,
  llRequestDisplayName,
  // detected
  llDetectedKey,
  llDetectedName,
  llDetectedOwner,
  llDetectedGroup,
  llDetectedPos,
  llDetectedRot,
  llDetectedVel,
  llDetectedType,
  llDetectedLinkNumber,
  llDetectedGrab,
  llDetectedTouchPos,
  // hash
  llMD5String,
  llSHA1String,
  llSHA256String,
  llHMAC,
  // base64
  llStringToBase64,
  llBase64ToString,
  llIntegerToBase64,
  llBase64ToInteger,
  // object
  llSetText,
  llSetObjectDesc,
  llGetObjectDesc,
  llDie,
  llResetScript,
  // link info
  llGetLinkNumber,
  llGetNumberOfPrims,
  llGetLinkKey,
  llGetLinkName,
  // inventory
  llGetInventoryNumber,
  llGetInventoryName,
  llGetInventoryType,
  llGetInventoryKey,
  llGetInventoryCreator,
  llGetInventoryDesc,
  llGetInventoryAcquireTime,
  llGetInventoryPermMask,
  llGetNotecardLine,
  llGetNumberOfNotecardLines,
  // script control
  llResetOtherScript,
  llSetScriptState,
  llGetScriptState,
  // linkset data
  llLinksetDataWrite,
  llLinksetDataWriteProtected,
  llLinksetDataRead,
  llLinksetDataReadProtected,
  llLinksetDataDelete,
  llLinksetDataDeleteProtected,
  llLinksetDataDeleteFound,
  llLinksetDataReset,
  llLinksetDataAvailable,
  llLinksetDataCountKeys,
  llLinksetDataListKeys,
  llLinksetDataFindKeys,
  llLinksetDataCountFound,
}
